server:
  port: 8761

spring:
  application:
    name: eureka
eureka:
  instance:
    #设置当前实例的主机名称
    hostname: localhost
    #定义服务失效的时间，单位：秒
    lease-expiration-duration-in-seconds: 20
    #定义服务续约任务（心跳）的调用间隔，单位：秒
    lease-renewal-interval-in-seconds: 10
    #不使用主机名来定义注册中心的地址，而使用IP地址的形式，如果设置了属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #IP地址
    ip-address: localhost
    #状态页面的URL，相对路径，默认使用 HTTP 访问，如果需要使用 HTTPS则需要使用绝对路径配置
    status-page-url-path: /info
    #健康检查页面的URL，相对路径，默认使用 HTTP 访问，如果需要使用 HTTPS则需要使用绝对路径配置
    health-check-url-path: /health
    #健康检查页面的URL，绝对路径
    health-check-url: /
  client:
    #是否注册为服务 服务端必配，禁止自生注册
    register-with-eureka: false
    #是否检索服务 服务端必配，表示自己就是注册中心，不需要去检索服务
    fetch-registry: false
    #eureka默认空间的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
  server:
    #关闭自我保护(生产时打开该选项) 关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
    enable-self-preservation: false
    #扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 10000
